version: "3.9"

services:
  postgres:
    image: postgres
    container_name: pg-mainimai
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    # volumes:
    #   - pg_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    # volumes:
    #   - ./minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: backend
#     env_file: .env
#     depends_on:
#       - postgres
#       - redis
#       - minio
#     ports:
#       - "8000:8000"
#     command: >
#       uvicorn app.main:app --reload --reload-exclude renders/*
#     volumes:
#       - ./backend:/app

#   worker:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: worker
#     env_file: .env
#     depends_on:
#       - redis
#       - postgres
#       - minio
#     command: celery -A app.tasks.celery worker --loglevel=info --concurrency=2
#     volumes:
#       - ./backend:/app


# # volumes:
# #   pg_data:
# #   minio-data:
